<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-9738CE5M" ignored="0" name="Ecommerce DressesPage" tests="4" failures="2" timestamp="30 Sep 2020 09:31:22 GMT" time="23.301" errors="0">
  <testcase name="Numberdresses" time="3.074" classname="com.qa.tests.DressesPageTest">
    <failure type="java.lang.AssertionError" message="expected [5] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [1]
at com.qa.tests.DressesPageTest.Numberdresses(DressesPageTest.java:24)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Numberdresses -->
  <testcase name="Listdresses" time="0.184" classname="com.qa.tests.DressesPageTest">
    <failure type="java.lang.AssertionError" message="lists don&amp;apos;t have the same size expected [5] but found [4]">
      <![CDATA[java.lang.AssertionError: lists don't have the same size expected [5] but found [4]
at com.qa.tests.DressesPageTest.Listdresses(DressesPageTest.java:33)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- Listdresses -->
  <testcase name="Pricedresses" time="0.195" classname="com.qa.tests.DressesPageTest"/>
  <testcase name="Discountdresses" time="0.097" classname="com.qa.tests.DressesPageTest"/>
</testsuite> <!-- Ecommerce DressesPage -->
